aa_kbc_params = "cc_kbc::KBS_IP_ADDRESS:KBS_PORT_NUMBER"
debug_console = true
dev_mode = false
log_level = "debug"
#hotplug_timeout = 3
debug_console_vport = 1026
log_vport = 0
container_pipe_size = 0
server_addr = "vsock://-1:1024"
unified_cgroup_hierarchy = false
tracing = false

[endpoints]
allowed = [
        "AddARPNeighborsRequest",
        "AddSwapRequest",
        "CloseStdinRequest",
        "CopyFileRequest",
        "CreateContainerRequest",
        "CreateSandboxRequest",
        "DestroySandboxRequest",
        "ExecProcessRequest",
        "GetMetricsRequest",
        "GetOOMEventRequest",
        "GuestDetailsRequest",
        "ListInterfacesRequest",
        "ListRoutesRequest",
        "MemHotplugByProbeRequest",
        "OnlineCPUMemRequest",
        "PauseContainerRequest",
        "PullImageRequest",
        "ReadStreamRequest",
        "ReseedRandomDevRequest",
        "RemoveContainerRequest",
        "ResumeContainerRequest",
        "SetGuestDateTimeRequest",
        "SignalProcessRequest",
        "StartContainerRequest",
        "StartTracingRequest",
        "StatsContainerRequest",
        "StopTracingRequest",
        "TtyWinResizeRequest",
        "UpdateContainerRequest",
        "UpdateInterfaceRequest",
        "UpdateRoutesRequest",
        "WaitProcessRequest",
        "WriteStreamRequest"
        ]
